server:
  port: 8108

general-properties:
  name: products
  bbog-api-key: ${LAB-BBOG-API-KEY:rtAtgtGdWy1GB0022Bhg04THR1j9bE7K3Vy41hOa}

management:
  endpoints:
    web:
      base-path: '/'
  endpoint:
    info:
      sensitive: false
      enabled: true
    health:
      sensitive: false
      enabled: true

info:
  owner: Fredy Guerrero <fredy.guerrero@avaldigitallabs.com>
  pod: the-simpsons
cache:
  specification: maximumSize=100
api-services:
  timeout: 10000
  keystore:
    file: ${keystore_file:src/main/resources/certificate/adl-pb.avaldigitallabs.com.jks}
    credential: ${SECURITY_KEYSTORE_CREDENTIAL:Datapower}
  oauthProperties:
    client-id: ${API_CONNECT_CLIENT_ID:9a76b4b5c7a9d2abe96f12d137aca8c4}
    client-secret: ${API_CONNECT_CLIENT_SECRET:3ad097242e6cb969c7bb093c9edeba90}
    grant-type: client_credentials
    scope: scope1
    auth-endpoint: ${API_CONNECT_ENDPOINT:https://apicapi-gateway-qa.appsptqa.ath.com.co/org-qa/api-pb/}
    auth-resource: v1/Authentication/oauth2/token
    skip-oauth: false
    certificate-required: true
  info:
    id: bbog-pb-backend-products
    url: ${API_CONNECT_ENDPOINT:https://apicapi-gateway-qa.appsptqa.ath.com.co/org-qa/api-pb/}
    resource-map:
      product-list: customerManagement/v3/Customer_Products/Products
      product-cards: customerManagement/v1/Administration_Products/Products/Cards
      loyalty-program: customerManagement/v1/Customer_Loyalty/Loyalty/Balance
      loyalty-transactions: customerManagement/v1/Customer_Loyalty/Loyalty/Transactions

manager-adapter-integration:
  integration-properties:
    adapter-integration:
      base-url: ${unicef_adapter_endpoint:https://api-logistics-management.labdigitalbdbtvsqa.com/V1}/
      timeout: 10000
      resource-map:
        unicef-adapter-call-enabled: true
        unicef-enrollment: Utility/logistics/DebitCard/delivery
        unicef-api-key: ${unicef_api_key:nhY5Zow1u416100SLCJEYcAzzI4FCIQ8DUj67wtd}
    campaign-adapter:
      base-url: ${LAB-BBOG-API:https://api-staging.bancodebogota.co/}
      timeout: 10000
      resource-map:
        customer-campaign: credito/campaign/customer-campaign

amazon:
  dynamodb:
    #endpoint: ${DYNAMO_HOST:http://localhost:8000/}
    prefix: ${BDB_APPLICATION_CHANNEL:yb-pb}-
    ttl: 24

api-connect-integration:
  enabled: true
elastic-integration:
  enabled: true

#Analytic and datalake parameters
analytics:
  enabled: true
